_BASE_: "../Base.yaml"

MODEL:
  WEIGHTS: ""

DATASETS:
  TRAIN: ("totaltext_train","mlt","ic13_train","ic15_train",)
  TEST: ("totaltext_test",)

SOLVER:
  IMS_PER_BATCH: 8
  BASE_LR: 1e-4
  LR_BACKBONE: 1e-5
  WARMUP_ITERS: 0
  STEPS: (85000,)
  MAX_ITER: 100000
  CHECKPOINT_PERIOD: 10000

TEST:
  EVAL_PERIOD: 10000

OUTPUT_DIR: ""