_BASE_: "../Base.yaml"

MODEL:
  WEIGHTS: ""

DATASETS:
  TRAIN: ("totaltext_train",)
  TEST: ("totaltext_test",)

SOLVER:
  IMS_PER_BATCH: 8
  BASE_LR: 1e-5
  LR_BACKBONE: 1e-6
  WARMUP_ITERS: 0
  STEPS: (100000,)  # no step
  MAX_ITER: 20000
  CHECKPOINT_PERIOD: 2000

TEST:
  EVAL_PERIOD: 2000

OUTPUT_DIR: ""